### ISSUE TITLE
So how do you use this on Windows?

### ISSUE THREAD

**Issue by rcdailey** [go2sh/cmake-integration-vscode#32]
I want to use Ninja generator with the MSVC compiler. How do I do this on Windows? Is there a step by step guide?

**Comment by go2sh** [comment]
Have you tried to download ninja and added it to the PATH variable? Should be sufficient, but I have never tried it.

**Comment by mmanyen** [comment]
I use it with ninja and windows, but I use the Minw64 compiler

**Comment by hriekehof** [comment]
I had some troubles using Visual Studio Community 2017 with ninja. There is also not alot of good information on this topic. I'm not an expert in VS but it seems that the build environment is quite path and environment dependent.  For example [here](https://stackoverflow.com/questions/31262342/cmake-g-ninja-on-windows-specify-x64) is an example without cmake integration. It seems that you have to set the compiler environment accordingly with `vcvarsall.bat` in one shell. Then you can call ninja.

 At the moment i just use the VS2017 generator instead of ninja and i can still build from VS Code using this nice extension.

**Comment by go2sh** [comment]
I'll try to create a tutorial section in the docs. But it might take some time. Maybe someone like to volunteer. ;-).

**Comment by go2sh** [comment]
Feel free to open a new issue, If you found a bug or have a feature request.
