### ISSUE TITLE
Does CMake Integration replace CMake Tools?

### ISSUE THREAD

**Issue by Yzrsah** [go2sh/cmake-integration-vscode#9]
Please provide some basic docs about CMake Integration *vs* the CMake Tools extension

- Differences between CMake Integration and CMake Tools extensions
- Some key points to use CMI instead of CMT

If the extensions are incompatible, then you should also remind the user to disable other extensions such as CMake Tools.

**Comment by atar-axis** [comment]
I would say that CMake Tools utilitizes CMake - without writing a single Line of CMake code, while on the others side CMake Integration does parse the already written CMake Project structure and integrates the information gathered from it, into vscode.

**Comment by go2sh** [comment]
Both extension basically try to do the same and they are somewhat incompatible as they share some settings, keybindings and both operate on the build directory. 

CMake Tools has a few drawbacks, which made me to start this extension:
 - No multi workspace folder support
 - No multi workspace folder dependencies

For me, the goal of this extension is to fully replace CMake Tools and provide the same set of features at least. In my own projects, I already did that.

Initially, I thought about adding those things to CMake Tools, but the code base has some major design flaws, which meant that the extension had to be rewritten anyways. Furthermore, CMake Tools uses rollbar, which I'am not a big fan of due to data protection concerns.

This extension currently lacks some features, that CMake Tools already has:
 - Build Configuration (aka Kits and Variants)
 - CMake Tree View

If you find any bug or you are missing a feature, feel free to create a new issue. I'll add a reminder to the README to disable the CMake Tools Extension as both are incompatible.

**Comment by hriekehof** [comment]
What about the Cpp-tools integration from Microsoft for intellisense ? This is also a nice feature in the cmake-tools extension

**Comment by go2sh** [comment]
@hriekehof This extension has it also. In addition to the cmake-tools extension , It provides infos for non source files (like header etc.) for all workspace folders.

**Comment by go2sh** [comment]
Add added a remark to the readme about the incompatibility.
